### ISSUE TITLE
NameError: name 'BesselKernel' is not defined

### ISSUE THREAD

**Issue by nachitoys** [shogun-toolbox/shogun#2855]
Hi... Im trying to generate a combined kernel and including a BesselKernel, but the following error is given:
```
Traceback (most recent call last):
  File "mkl2.py", line 47, in <module>
    kernels.append(BesselKernel(l = feats_train, r = feats_train, order = 0, width = 5, degree = 1))
NameError: name 'BesselKernel' is not defined
```
How I can solve it? It is necessary adding in some way the kernel code (available at the Class reference) to my Shogun installation?

Taking advantage of this public space, also I would like to know if MKL works for non-symmetric kernels like the aforementioned or perhaps the Chi2. The paper you cited (Bach, 2004) in the MKL proposal (Sonnenburg, 2006) assumes symmetric and PD subkernels, but I have the doubt. 

Thank you very much guys...﻿

**Comment by lisitsyn** [comment]
@nachitoys for some reason swig interface for bessel kernel was missed. I am going to add it in a minute.

Not sure about non-symmetric kernels but probably it won't work well. Following Mercer theorem kernel is symmetric and PD.

**Comment by nachitoys** [comment]
Hi @lisitsyn, Thank you for answer. How I can add these changes to my installation?

**Comment by lisitsyn** [comment]
@nachitoys if you compile from sources - just update to the latest revision of the develop branch. In case you use some release I have bad news - sources are required :)

**Comment by nachitoys** [comment]
Hi @lisitsyn, I think I compiled from sources, so I made this:

```
$ cd shogun
~/shogun$ ls
applications  ChangeLog       configs            data      NEWS       src
benchmarks    cmake           COPYING            doc       README.md  tests
build         CMakeLists.txt  CTestConfig.cmake  examples  scripts
~/shogun$ git pull
remote: Counting objects: 190, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 190 (delta 138), reused 138 (delta 138), pack-reused 45
Receiving objects: 100% (190/190), 97.81 KiB | 80.00 KiB/s, done.
Resolving deltas: 100% (148/148), completed with 53 local objects.
From git://github.com/shogun-toolbox/shogun
   308e63c..2cbeed7  develop    -> origin/develop
Updating 308e63c..2cbeed7
Fast-forward
 benchmarks/elementwise_benchmark.cpp               |  26 ++--
 src/interfaces/modular/Kernel.i                    |  16 ++
 src/interfaces/modular/Kernel_includes.i           |  13 +-
 src/shogun/base/SGObject.cpp                       |   1 +
 src/shogun/io/SGIO.h                               |   2 +-
 src/shogun/machine/GaussianProcessMachine.cpp      |   2 +
 src/shogun/machine/gp/EPInferenceMethod.cpp        |  22 ++-
 src/shogun/machine/gp/EPInferenceMethod.h          |   5 +-
 src/shogun/machine/gp/ExactInferenceMethod.cpp     |  24 ++-
 src/shogun/machine/gp/ExactInferenceMethod.h       |   5 +-
 src/shogun/machine/gp/FITCInferenceBase.cpp        |  45 +++---
 src/shogun/machine/gp/FITCInferenceBase.h          |  18 ++-
 src/shogun/machine/gp/FITCInferenceMethod.cpp      |  20 ++-
 src/shogun/machine/gp/FITCInferenceMethod.h        |   2 +
 src/shogun/machine/gp/InferenceMethod.cpp          |  11 +-
 src/shogun/machine/gp/InferenceMethod.h            |   8 +-
 src/shogun/machine/gp/KLInferenceMethod.cpp        |  23 ++-
 src/shogun/machine/gp/KLInferenceMethod.h          |   5 +-
 src/shogun/machine/gp/LaplacianInferenceBase.cpp   |  18 ++-
 src/shogun/machine/gp/LaplacianInferenceBase.h     |   4 +-
 .../machine/gp/MultiLaplacianInferenceMethod.cpp   |   3 +-
 src/shogun/machine/gp/SingleFITCLaplacianBase.cpp  | 170 +++++++++++++++++++--
 src/shogun/machine/gp/SingleFITCLaplacianBase.h    |  84 ++++++++++
 .../gp/SingleFITCLaplacianInferenceMethod.cpp      |  34 +++--
 .../gp/SingleFITCLaplacianInferenceMethod.h        |   5 +-
 .../machine/gp/SingleLaplacianInferenceMethod.cpp  |   7 +-
 .../machine/gp/SingleLaplacianInferenceMethod.h    |   2 +-
 .../implementation/ElementwiseUnaryOperation.h     |   2 +-
 .../internal/implementation/operations/Parameter.h | 126 +++++++++++++++
 .../mathematics/linalg/internal/opencl_util.h      |  60 +++++++-
 src/shogun/neuralnets/NeuralNetwork.cpp            |  25 +++
 src/shogun/neuralnets/NeuralNetwork.h              |   2 +-
 tests/unit/base/SGObject_unittest.cc               |  90 +++++++++++
 tests/unit/machine/gp/InferenceMethod_unittest.cc  |  67 +++++++-
 .../linalg/ElementwiseOperations_unittest.cc       | 124 ++++++++-------
 35 files changed, 905 insertions(+), 166 deletions(-)
 create mode 100644 src/shogun/mathematics/linalg/internal/implementation/operations/Parameter.h
~/shogun$ cd
~$ python mkl2.py
Traceback (most recent call last):
  File "mkl2.py", line 50, in <module>
    kernels.append(BesselKernel(l = feats_train, r = feats_train, order = 0, width = 5, degree = 1))
NameError: name 'BesselKernel' is not defined
```
As you see, the error remains. What I could doing wrong?

**Comment by lisitsyn** [comment]
@nachitoys just to be sure - did you recompile and install it once you updated git?

**Comment by nachitoys** [comment]
Hi @lisitsyn, I did this: 
```
~$ cd shogun/build
~/shogun/build$ cmake ..
-- Could NOT find CCache (missing:  CCACHE) 
-- Using system's malloc
-- Could NOT find GDB (missing:  GDB_COMMAND GDB_VERSION) 
-- Could NOT find MOSEK (missing:  MOSEK_DIR MOSEK_INCLUDE_DIR MOSEK_LIBRARY) 
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Could NOT find ATLAS (missing:  ATLAS_LIBRARIES ATLAS_INCLUDES) 
-- Could NOT find CBLAS (missing:  CBLAS_LIBRARY) 
-- Could NOT find GLPK (missing:  GLPK_LIBRARY GLPK_INCLUDE_DIR GLPK_PROPER_VERSION_FOUND) 
-- Could NOT find CPLEX (missing:  CPLEX_LIBRARY CPLEX_INCLUDE_DIR) 
-- Could NOT find OPENCL (missing:  OPENCL_LIBRARY OPENCL_INCLUDE_DIR) 
-- Could NOT find ViennaCL (missing:  VIENNACL_INCLUDE_DIR OPENCL_INCLUDE_DIRS OPENCL_LIBRARIES) (Required is at least version "1.5.0")
-- checking for one of the modules 'libColPack>=1.0.9;ColPack>=1.0.9'
-- Could NOT find NLOPT (missing:  NLOPT_LIBRARY NLOPT_INCLUDE_DIR) 
-- Could NOT find LPSOLVE (missing:  LPSOLVE_LIBRARIES LPSOLVE_INCLUDE_DIR) 
-- Could NOT find ColPack (missing:  COLPACK_LIBRARIES COLPACK_LIBRARY_DIR COLPACK_INCLUDE_DIR) 
-- Could NOT find ARPREC (missing:  ARPREC_LIBRARIES ARPREC_INCLUDE_DIR) 
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- checking for one of the modules 'libjson>=0.11;json>=0.11;json-c>=0.11'
-- Could NOT find LibXml2 (missing:  LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIR) 
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS) 
-- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR) 
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
-- Could NOT find LibLZMA (missing:  LIBLZMA_INCLUDE_DIR LIBLZMA_LIBRARY LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) 
-- Could NOT find SNAPPY (missing:  SNAPPY_LIBRARIES SNAPPY_INCLUDE_DIR) 
-- Lzo includes and libraries NOT found. 
-- Spinlock support found
-- Could NOT find PROTOBUF (missing:  PROTOBUF_LIBRARY PROTOBUF_INCLUDE_DIR) 
-- Supported backend(s) for linear algebra FOUND and ENABLED
-- ===================================================================================================================
-- Summary of Configuration Variables
-- 
-- The following OPTIONAL packages have been found:

 * OpenMP
 * BLAS
 * LAPACK
 * Eigen3 (required version >= 3.1.2)
 * Spinlock
 * Threads

-- The following REQUIRED packages have been found:

 * SWIG (required version >= 2.0.4)
 * PythonLibs
 * PythonInterp
 * NumPy

-- The following OPTIONAL packages have not been found:

 * CCache
 * GDB
 * Mosek
 * Atlas
 * CBLAS
 * GLPK
 * CPLEX
 * ARPACK
 * ViennaCL (required version >= 1.5.0)
 * NLopt
 * LpSolve
 * ColPack
 * ARPREC
 * Doxygen
 * LibXml2
 * HDF5
 * CURL
 * ZLIB
 * BZip2
 * LibLZMA
 * SNAPPY
 * LZO
 * Protobuf

-- The following REQUIRED packages have not been found:

 * OpenCL

-- ===================================================================================================================
-- Enabled Integration
--   OpenCV Integration is OFF 	 - enable with -DOpenCV=ON
-- ===================================================================================================================
-- Enabled Interfaces
--   libshogun is ON
--   python modular is ON
--   octave modular is OFF 	 - enable with -DOctaveModular=ON
--   java modular is OFF 	 - enable with -DJavaModular=ON
--   perl modular is OFF 	 - enable with -DPerlModular=ON
--   ruby modular is OFF 	 - enable with -DRubyModular=ON
--   csharp modular is OFF 	 - enable with -DCSharpModular=ON
--   R modular is OFF 		 - enable with -DRModular=ON
--   lua modular is OFF 	 - enable with -DLuaModular=ON
-- 
-- Enabled legacy interfaces
--   cmdline static is OFF 	 - enable with -DCmdLineStatic=ON
--   python static is OFF 	 - enable with -DPythonStatic=ON
--   octave static is OFF 	 - enable with -DOctaveStatic=ON
--   matlab static is OFF 	 - enable with -DMatlabStatic=ON
--   R static is OFF 		 - enable with -DRStatic=ON
-- ===================================================================================================================
-- To compile shogun type
--   make
-- 
-- To install shogun to /home/iarroyof/shogun-install type
--   make install
-- 
-- or to install to a custom directory
--   make install DESTDIR=/my/special/path
--   (or rerun cmake with -DCMAKE_INSTALL_PREFIX=/my/special/path) to just change the prefix
-- ===================================================================================================================
-- Configuring done
-- Generating done
-- Build files have been written to: /home/iarroyof/shogun/build
~/shogun/build$ make all
[  0%] Generating /home/iarroyof/shogun/src/shogun/base/class_list.cpp
[  0%] Built target class_list
[  1%] Generating version header
[  1%] Built target version
[  1%] Generating /home/iarroyof/shogun/src/shogun/base/class_list.cpp
Scanning dependencies of target libshogun
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/labels/DenseLabels.cpp.o
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/labels/BinaryLabels.cpp.o
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/labels/MultilabelLabels.cpp.o
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/labels/StructuredLabels.cpp.o
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/labels/FactorGraphLabels.cpp.o
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/labels/Labels.cpp.o
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/labels/RegressionLabels.cpp.o
[  2%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/labels/LabelsFactory.cpp.o
[  3%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/labels/MulticlassLabels.cpp.o
[  3%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/labels/LatentLabels.cpp.o
[  3%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/modelselection/ModelSelectionParameters.cpp.o
[  3%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/modelselection/ParameterCombination.cpp.o
[  3%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/modelselection/GridSearchModelSelection.cpp.o
[  3%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/modelselection/RandomSearchModelSelection.cpp.o
[  3%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/modelselection/ModelSelection.cpp.o
[  4%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/modelselection/GradientModelSelection.cpp.o
[  4%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/DistanceMachine.cpp.o
[  4%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/OnlineLinearMachine.cpp.o
[  4%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/LinearLatentMachine.cpp.o
[  4%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/MulticlassMachine.cpp.o
[  4%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/LinearStructuredOutputMachine.cpp.o
[  4%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/KernelMachine.cpp.o
[  4%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/KernelMulticlassMachine.cpp.o
[  5%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/BaseMulticlassMachine.cpp.o
[  5%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/StructuredOutputMachine.cpp.o
[  5%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/LinearMachine.cpp.o
[  5%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/BaggingMachine.cpp.o
[  5%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/RandomForest.cpp.o
[  5%] Building CXX object src/shogun/CMakeFiles/libshogun.dir/machine/GaussianProcessMachine.cpp.o
/home/iarroyof/shogun/src/shogun/machine/GaussianProcessMachine.cpp: In member function ‘shogun::SGVector<double> shogun::CGaussianProcessMachine::get_posterior_means(shogun::CFeatures*)’:
/home/iarroyof/shogun/src/shogun/machine/GaussianProcessMachine.cpp:90:16: error: ‘class shogun::CSingleFITCLaplacianBase’ has no member named ‘optimize_inducing_features’
   fitc_method->optimize_inducing_features();
                ^
/home/iarroyof/shogun/src/shogun/machine/GaussianProcessMachine.cpp: In member function ‘shogun::SGVector<double> shogun::CGaussianProcessMachine::get_posterior_variances(shogun::CFeatures*)’:
/home/iarroyof/shogun/src/shogun/machine/GaussianProcessMachine.cpp:154:16: error: ‘class shogun::CSingleFITCLaplacianBase’ has no member named ‘optimize_inducing_features’
   fitc_method->optimize_inducing_features();
                ^
make[2]: *** [src/shogun/CMakeFiles/libshogun.dir/machine/GaussianProcessMachine.cpp.o] Error 1
make[1]: *** [src/shogun/CMakeFiles/libshogun.dir/all] Error 2
make: *** [all] Error 2
```
As you can see. An error persists in recompiling. What is wrong?

Thank you

**Comment by lisitsyn** [comment]
@nachitoys sorry for long answer. This looks like at some point the build was broken. I suggest you to try again with latest `develop`

**Comment by erip** [comment]
Recommend closing.
