### ISSUE TITLE
Setting (loading) MKL pretrained (model) subkernel weights

### ISSUE THREAD

**Issue by iarroyof** [shogun-toolbox/shogun#2929]
Hi all.

Im trying to figure out how to use a vector of pretrained subkernel weights for the MKL module. Im trying to understand this post (script):

http://shogun-list.shogun-toolbox.narkive.com/Ff1tmKJM/set-subkernel-weights-does-not-work-in-python-modular-interface

however, in the mentioned script, Im not sure how `mkl.classify()` works without previously executing `mkl.set_kernel(kernel)`, given `kernel` was modified by `kernel.set_subkernel_weights(w, 3)`. Can someone explain this segment of the script or point me to some other clearer one where pretrained weights are loaded and applied?

Thank you very much...

**Comment by iglesias** [comment]
Hi @iarroyof. Are you obtaining the weights using Shogun or from somewhere else? In case you are also using Shogun for the training, maybe using serialization solves your problem. See for instance serialization_string_kernels_modular.py or other serialization examples.

**Comment by iarroyof** [comment]
Hi @iglesias thank you for reply. Actually mi question is in the sense Im not sure what is the procedure to update que subkernel weights of a combinedKernel and then, applying this update to new data via a MKL object. My MKL Shogun object is already trained. Its subkernel weights are stored into a file. They can be retrieved at any time as a python list. 

I'd like to instantiate a completely new MKL object, in such a way transferring the stored (pretrained) weights to it is possible. I'd like this new MKL object can work just like a newly trained one (but using pretrained weights instead).

**Comment by iarroyof** [comment]
Hi again... I have tried with this code:
```
from modshogun import *
from tools.load import LoadMatrix
from mklObj import genKer
from numpy import array

[traindata, 
  testdata, 
  trainlab, 
  testlab] = load_Toy('/home/iarroyof/shogun-data/toy/',	# Data directory
		       'fm_train_multiclass_digits500.dat',		# Multiclass dataSet examples file name
		       'label_train_multiclass_digits500.dat')	# Multiclass Labels file name

feats_train = RealFeatures(traindata) 	# train examples
labelsTr = MulticlassLabels(trainlab)	# train multiclass labels
feats_test = RealFeatures(testdata)  	# test examples
labelsTs = MulticlassLabels(testlab)	# test multiclass labels		   

# Parameters
kernelFamily = 'gaussian'
sigmas = [10, 20, 70, 120]
weights = array([0.1, 0.1, 0.3, 0.5])

# Setting up the MKL machine
mkl = MKLMulticlass()		            
# Generating a combinedKernel
kernel = genKer(featsL = feats_train, featsR = feats_test, basisFam = kernelFamily, widths = sigmas) 
kernel.init(feats_train, feats_test)
kernel.set_subkernel_weights(weights)      # Setting pretrained weights 
mkl.set_kernel(kernel)
mkl.set_labels(labelsTs)

out = mkl.apply()   # Applying 
# Evaluating the test performance
evalua = MulticlassAccuracy()
testerr = evalua.evaluate(out, labelsTs)
print 'Kernel evaluation ready. The precision was: ', testerr*100, '%'
```
After trying to run, the following error is given:
`Traceback (most recent call last):
  File "mkl2.py", line 81, in <module>
    out = mkl.apply()                     
SystemError: [ERROR] In file /home/iarroyof/shogun/src/shogun/machine/MulticlassMachine.cpp line 113: num_machines = 0, did you train your machine?`

**Comment by iarroyof** [comment]
Hi... I have kept trace of this problem. By testing different situations with the code of my previous post I have inferred the way is loading a pretrained MKL machine (please correct me if it not (too) necessary). In this direction, I have tested  `MKLClassification.save()` by using the next code snippet:
```
# ... MKL object instantiation, parameter setting, kernel generation and initialization...
mkl.train()
f = open('mkl_saved.mkl', 'w')
mkl.save(f)

mkl.load(f)
sigmas = [10, 20, 70, 120]
weights = array([0.1, 0.1, 0.3, 0.5])
kernel = genKer(featsL = feats_train, featsR = feats_test, 
                        basisFam = kernelFamily, widths = sigmas)
kernel.set_subkernel_weights(weights)
kernel.init(feats_train, feats_test)
mkl.set_kernel(kernel)
mkl.set_labels(labelsTs)
out = mkl.apply()

```
However, the next error is given:
```
Traceback (most recent call last):
  File "mkl2.py", line 56, in <module>
    mkl.save(f)
TypeError: in method 'CSVM_save', argument 2 of type 'FILE *'
```
Which made me to think there is a problem with the Shogun Python wrapping, so I review the implementation of `save()`. I noted it is needed uniquely saving some specific components of the MKL inner SVM. Again, necessary methods for retrieving these components seem to be also unavailable for the Python interface.

**Comment by iglesias** [comment]
All right, let's try to go one part at a time.

- I am not familiarised with the implementation of MKL so perhaps it is actually required to call train in an MKL object before you can call apply. Maybe some internal trained state is set upon call to train and it is checked before calling apply, failing the call if the trained state has not been set.

Would cloning the MKL trained object solve your problem?

The C++ example you have cited above is not the same as what you are doing in your Python code. Note that in the C++ example tsvm has been trained before setting the kernel.

- I am unsure about they way you are using save to serialize. The serialization Python examples and also in some code I used in the past I used pickle.

**Comment by iarroyof** [comment]
Thank you @iglesias, I will try by serializing... 

PD. The code I used is updated...

**Comment by iglesias** [comment]
Keep us updated about your progress and feel free to close the issue once you consider it solved.

**Comment by iarroyof** [comment]
Thank you @iglesias. Do know if this code snippet is correct?:
```
mkl.train()
f = open('mkl_saved.mkl', 'w')
mkl.save(f)
```
output: `TypeError: in method 'CSVM_save', argument 2 of type 'FILE *'`

or it is needed convert `f` to another data type, before passing it to the mkl `save()` method.

**Comment by iarroyof** [comment]
Hi... I reimplemented saving and loading method for Python. Here is an informal test code:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from modshogun import *
from tools.load import LoadMatrix
from mklObj import genKer
from mklObj import load_binData
from numpy import *

# Loading toy data from files
[feats_train, feats_test, labelsTr, labelsTs] = load_binData(tr_ts_portion=0.75, 
                fileTrain='fm_ape_gutXX.dat',		# two-class dataSet examples file name
                fileLabels='bin_label_ape_gut.dat')	# two-class Labels file name

# Parameters
kernelFamily = 'gaussian'
mkl.set_C(1,1)
mkl.set_mkl_norm(2)
sigmas = [10, 20, 70, 120] # toy widths

# =============================== Training =============================================================
# some function for creating a one-time combined kernel
kernel = genKer(featsL = feats_train, featsR = feats_train, basisFam = kernelFamily, widths = sigmas) 
kernel.init(feats_train, feats_train)

# Setting up the MKL machine
mkl = MKLClassification()           # MKL object 
mkl.set_kernel(kernel)
mkl.set_labels(labelsTr)
mkl.train()
# Note: Do not to include sigmas because they are kernel family dependent
def save_mkl(mkl, kernel, file_name): # Function for saving a pretrained MKL machine
    mkl_machine = {}
    support=[]
    mkl_machine['num_support_vectors'] = mkl.get_num_support_vectors()
    mkl_machine['bias']=mkl.get_bias()
    for i in xrange(mkl_machine['num_support_vectors']): # whole vector setting methods (e.g. set_alphas()) have 
                                                         # problems, so we used individual setting methods and a
                                                         # for loop.
        support.append((mkl.get_alpha(i), mkl.get_support_vector(i)))
    mkl_machine['support'] = support
    mkl_machine['weights'] = list(kernel.get_subkernel_weights())
    
    f = open(file_name,'w')
    f.write(str(mkl_machine)+'\n')

save_mkl(mkl, kernel, 'mkl_saved.model') # Saving the pretrained MKL machine
del mkl
del kernel
# ================= Pretrained machine loading and tests ===========================================================
def load_mkl(file_name): # Function for loading a pretrained MKL machine.
    
    with open(file_name,'r') as pointer:
        mkl_machine = eval(pointer.read())
    
    mkl = MKLClassification()
    mkl.set_bias(mkl_machine['bias'])
    mkl.create_new_model(mkl_machine['num_support_vectors'])
    for i in xrange(mkl_machine['num_support_vectors']):
        mkl.set_alpha(i, mkl_machine['support'][i][0])
        mkl.set_support_vector(i, mkl_machine['support'][i][1])
    
    
    return mkl, array(mkl_machine['weights'])
 
[mkl_copy, ws] = load_mkl('mkl_saved.model') # Loading the pretrained MKL machine from file. Now it is used test data.
kernel_copy = genKer(featsL = feats_train, featsR = feats_test, basisFam = kernelFamily, widths = sigmas)
kernel_copy.set_subkernel_weights(ws)
kernel_copy.init(feats_train, feats_test)

mkl_copy.set_kernel(kernel_copy)
out = mkl_copy.apply()                      

evalua = ErrorRateMeasure()     # performance measures are computed.
testerr = 100 - evalua.evaluate(out, labelsTs) * 100
print testerr
```
In this way, think the issue is solved

**Comment by iarroyof** [comment]
Hi... I reimplemented saving and loading methods for Python. This implied saving not only pretrained weights but also components of the trained MKL model. These elements can be verified in the body of the `save_mkl()` method I have implemented to backup such a training model. Here is an informal test code:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from modshogun import *
from tools.load import LoadMatrix
from mklObj import genKer
from mklObj import load_binData
from numpy import *

# Loading toy data from files
[feats_train, feats_test, labelsTr, labelsTs] = load_binData(tr_ts_portion=0.75, # train data portion
                                                                 fileTrain='toy_data.dat',     # Two-class examples file name
                                                                 fileLabels='toy_labels.dat')	# Two-class Labels file name
# Parameters
kernelFamily = 'gaussian'
sigmas = [10, 20, 70, 120]

# =============================== Training ====================================
kernel = genKer(featsL = feats_train, featsR = feats_train, basisFam = kernelFamily, widths = sigmas)
kernel.init(feats_train, feats_train)
# Setting up the MKL machine
mkl = MKLClassification()           # origin MKL object 
mkl.set_C(1,1)
mkl.set_mkl_norm(2)
mkl.set_kernel(kernel)
mkl.set_labels(labelsTr)
mkl.train()                         # Train the origin machine
# Note: We preferred discarding sigmas from this file because they are kernel family dependent
def save_mkl(mkl, kernel, file_name): # Python reimplementated function for saving a pretrained MKL machine. 
    mkl_machine = {}
    support=[]
    mkl_machine['num_support_vectors'] = mkl.get_num_support_vectors()
    mkl_machine['bias']=mkl.get_bias()
    for i in xrange(mkl_machine['num_support_vectors']): 
        support.append((mkl.get_alpha(i), mkl.get_support_vector(i)))
        
    mkl_machine['support'] = support
    mkl_machine['weights'] = list(kernel.get_subkernel_weights())
    
    f = open(file_name,'w')
    f.write(str(mkl_machine)+'\n')
    f.close()
    
save_mkl(mkl, kernel, 'mkl_saved.model') # Saving the dictionary containing trained MKL machine into a file
del mkl

# ================= Pretrained machine tests =======================================
def load_mkl(file_name): # Python reimplemented function for loading a pretrained MKL machine.
    with open(file_name, 'r') as pointer:
        mkl_machine = eval(pointer.read())
    
    mkl = MKLClassification()           # A new two-class MKL object
    mkl.set_bias(mkl_machine['bias'])
    mkl.create_new_model(mkl_machine['num_support_vectors']) # Initialize the inner SVM
    for i in xrange(mkl_machine['num_support_vectors']):
        mkl.set_alpha(i, mkl_machine['support'][i][0])
        mkl.set_support_vector(i, mkl_machine['support'][i][1])
    
    return mkl, array(mkl_machine['weights'])
 
[mkl_copy, weights] = load_mkl('mkl_saved.model') # Loading the pretrained MKL machine. We now use test data.
kernel_copy=genKer(featsL = feats_train, featsR = feats_test, basisFam=kernelFamily, widths = sigmas)
kernel_copy.set_subkernel_weights(weights)        # Setting up pretrained weights to the new kernel
kernel_copy.init(feats_train, feats_test)
mkl_copy.set_kernel(kernel_copy)

out = mkl_copy.apply()                            # Test the loaded machine

evalua = ErrorRateMeasure()     # performance measures are computed.
testerr = 100 - evalua.evaluate(out, labelsTs) * 100
print testerr
```
In this way, I think the issue is solved only for two-class problems. I will try for regression model because I need it. For multiclass mkl object needed getter and setter methods weren't wrapped by Swig. I also confirmed `mkl.save()` as well as `mkl.load()` methods were not well wrapped by Swig (they showed errors like the mentioned in my previous post). Other needed mkl (two-class and multiclass) object methods have similar problems, e.g. `mkl.set_alphas()`, `mkl.load_alphas()`, `mkl.set_support_vectors()` and `mkl.load_support_vectors()`, etc.
