### ISSUE TITLE
add the requirement of the version of doxygen

### ISSUE THREAD

**Issue by yorkerlin** [shogun-toolbox/shogun#2959]
Compiling Shogun with -DPythonModular=ON  will fail if the version of doxygen is low (<1.8.6) .
The error will occur if the version of doxygen is low (<=1.8.5)
```
[ 84%] Generating modshogun_doxygen.i
Traceback (most recent call last):
  File "/home/wlin/shogun-shogun_4.0.0/src/.doxy2swig.py", line 450, in <module>
    main()
  File "/home/wlin/shogun-shogun_4.0.0/src/.doxy2swig.py", line 446, in main
    convert(args[0], args[1], not options.func_def, options.quiet)
  File "/home/wlin/shogun-shogun_4.0.0/src/.doxy2swig.py", line 425, in convert
    p.generate()
  File "/home/wlin/shogun-shogun_4.0.0/src/.doxy2swig.py", line 102, in generate
    self.parse(self.xmldoc)
  File "/home/wlin/shogun-shogun_4.0.0/src/.doxy2swig.py", line 111, in parse
    pm(node)
  File "/home/wlin/shogun-shogun_4.0.0/src/.doxy2swig.py", line 141, in parse_Element
    handlerMethod(node)
  File "/home/wlin/shogun-shogun_4.0.0/src/.doxy2swig.py", line 375, in do_doxygenindex
    p = Doxy2SWIG(fname, self.include_function_definition, self.quiet)
  File "/home/wlin/shogun-shogun_4.0.0/src/.doxy2swig.py", line 72, in __init__
    self.xmldoc = minidom.parse(f).documentElement
  File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1921, in parse
    return expatbuilder.parse(file)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 928, in parse
    result = builder.parseFile(file)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
xml.parsers.expat.ExpatError: mismatched tag: line 382, column 57
make[2]: *** [src/interfaces/python_modular/modshogun_doxygen.i] Error 1
make[1]: *** [src/interfaces/python_modular/CMakeFiles/python_doxy2swig.dir/all] Error 2
```

**Comment by yorkerlin** [comment]
@karlnapf

**Comment by karlnapf** [comment]
Thanks for pointing this out

We can easily require a certain doxygen version with changing the line

```cmake
FIND_PACKAGE(Doxygen)
```

in  `shogun/CMakeLists.txt` to

```cmake
FIND_PACKAGE(Doxygen 1.8.6)
```

Feel free to send a patch to do that. But before, *really* make sure that starting a build from scratch with that doxygen version causes the error your described.

**Comment by yorkerlin** [comment]
@karlnapf 
At least in a red hat server and my laptop (fedora), I get the same error when I build shogun (4.0 and develop version) with PythonModular=ON from scratch. The error disappears when doxygen is updated to 1.8.6.

**Comment by karlnapf** [comment]
Ok then I have sent a patch

**Comment by besser82** [comment]
@yorkerlin Which version of Fedora are you using?  [All active maintained versions of Fedora](https://apps.fedoraproject.org/packages/doxygen) ship doxygen >= 1.8.10.

For RHEL / CentOS / Scientific Linux, I can provide a recent version of doxygen through EPEL.
