### ISSUE TITLE
Cookbook generation failure missing responsible file indicator

### ISSUE THREAD

**Issue by arianepaola** [shogun-toolbox/shogun#3253]
Currently cookbook generation does not provide any debug information. Therefore erroneous translation files are hard to track down.

```
Example:
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vagrant/shogun/build
[4/5] Generating examples from meta-language
FAILED: cd /home/vagrant/shogun/build/examples/meta && /usr/bin/python /home/vagrant/shogun/examples/meta/generator/generate.py -i /home/vagrant/shogun/examples/meta/src -o /home/vagrant/shogun/build/examples/meta -t /home/vagrant/shogun/examples/meta/generator/targets -g /home/vagrant/shogun/build/src/shogun/tags --store-vars
Traceback (most recent call last):
  File "/home/vagrant/shogun/examples/meta/generator/generate.py", line 120, in <module>
    includedTargets=args.targets, storeVars=storeVars)
  File "/home/vagrant/shogun/examples/meta/generator/generate.py", line 44, in translateExamples
    targets.append(json.load(tFile))
  File "/usr/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
ninja: build stopped: subcommand failed.
```

**Comment by arianepaola** [comment]
@vigsterkr @karlnapf @lgoetz

Please review and merge.

**Comment by karlnapf** [comment]
BTW you can better paste code snippets using three "`" then it is displayed nicer

**Comment by arianepaola** [comment]
@karlnapf Hmm, I am using "`". Don't know why the output looks strange.

**Comment by karlnapf** [comment]
Its meant for single line code. Try use "``` [newline] [code] [newline]```"

**Comment by arianepaola** [comment]
this worked: "```" [code] "```"

**Comment by arianepaola** [comment]
@karlnapf note on IRC:
what about you put a try around it
and in case of an exception, you print
and then print the usual stack trace
keeping the output cleaner
