### ISSUE TITLE
Cookbook generation crashes using empty meta example files

### ISSUE THREAD

**Issue by arianepaola** [shogun-toolbox/shogun#3254]
Currently, when an empty meta example file is referenced for a cookbook the generation process crashes.

``Generating LALR tables
Generating LALR tables
Generating LALR tables
Generating LALR tables
Translating clustering/hierarchical.sg
Translating clustering/gmm.sg
Translating gaussian_processes/gaussian_process_regression.sg
Translating distance/tanimoto_distance.sg
Traceback (most recent call last):
  File "/home/vagrant/shogun/examples/meta/generator/generate.py", line 120, in <module>
    includedTargets=args.targets, storeVars=storeVars)
  File "/home/vagrant/shogun/examples/meta/generator/generate.py", line 52, in translateExamples
    ast = parse(file.read(), os.path.join(dirRelative, filename))
  File "/home/vagrant/shogun/examples/meta/generator/parse.py", line 241, in parse
    return parser.parse(programString, filePath)
  File "/home/vagrant/shogun/examples/meta/generator/parse.py", line 28, in parse
    if programString[-1] != "\n":
IndexError: string index out of range
ninja: build stopped: subcommand failed.``

**Comment by arianepaola** [comment]
@vigsterkr @karlnapf @lgoetz

Please review and merge.
