### ISSUE TITLE
fix error in variational_classifier.ipynb

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#3757]
```
[NbConvertApp] ERROR | Error while converting '/home/buildslave/nightly_default/build/doc/ipython-notebooks/gaussian_process/variational_classifier.ipynb'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/nbconvertapp.py", line 357, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/exporter.py", line 165, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/exporter.py", line 183, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/html.py", line 65, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/templateexporter.py", line 200, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/exporter.py", line 130, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/exporter.py", line 302, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb,resources)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/preprocessors/execute.py", line 145, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/preprocessors/base.py", line 70, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/preprocessors/execute.py", line 176, in preprocess_cell
    raise CellExecutionError(msg)
CellExecutionError: An error occurred while executing the following cell:
------------------
#Since inducing points are generated by random, decision boundary of SingleFITCLaplace could be different if random seed is different
np.random.seed(3)
input_path=os.path.join(SHOGUN_DATA_DIR, 'toy/banana.dat)'
n_inducing_points=8
plot_large_scale_with_inducing_points(input_path,n_inducing_points)
------------------

SyntaxError: invalid syntax (<ipython-input-15-7dcd9a5a5525>, line 4)
```

**Comment by minxuancao** [comment]
I ran the ipython notebook in jupyter and got the following error.
![screen shot 2017-03-30 at 11 13 56 pm](https://cloud.githubusercontent.com/assets/8654851/24535249/e5409780-15a0-11e7-9b7d-a3c253ee4900.png)
I think Error code(5) means access is denied somewhere but I don't know where...

**Comment by yorkerlin** [comment]
@minxuancao  this is not an error. It is a warning. The minimizer stops due to some reason. The reason is coded in NLOPT. Please see the error code (e.g. 5 in this case) defined in NLOPT.

**Comment by deveshnag1** [comment]
@vigsterkr is it because of a misplace in position of " ' " in this line?
input_path=os.path.join(SHOGUN_DATA_DIR, 'toy/banana.dat)'

**Comment by vigsterkr** [comment]
@deveshnag1 most probably... then again the task is to check and solve this issue :)

**Comment by deveshnag1** [comment]
@vigsterkr How do I check it? In a jupyter notebook?

**Comment by vigsterkr** [comment]
@deveshnag1 i'm not so sure how you've tested that notebook as although the particular error is gone from the notebook but there's other now:

```
[NbConvertApp] ERROR | Error while converting '/home/buildslave/nightly_default/build/doc/ipython-notebooks/gaussian_process/variational_classifier.ipynb'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/nbconvertapp.py", line 357, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/exporter.py", line 165, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/exporter.py", line 183, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/html.py", line 65, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/templateexporter.py", line 200, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/exporter.py", line 130, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/exporter.py", line 302, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb,resources)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/preprocessors/execute.py", line 145, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/preprocessors/base.py", line 70, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/usr/local/lib/python2.7/dist-packages/nbconvert/preprocessors/execute.py", line 176, in preprocess_cell
    raise CellExecutionError(msg)
CellExecutionError: An error occurred while executing the following cell:
------------------
#an example for the sonar data set
train_size=108
(x_train, y_train, x_test, y_test, B)=extract(os.path.join(SHOGUN_DATA_DIR, 'uci/sonar/sonar.all-data', train_size))
inference_methods =[
                  KLDualInferenceMethod,
                  SingleLaplaceInferenceMethod,
                  SingleLaplaceInferenceMethod,
                  KLDiagonalInferenceMethod,
                  #KLCholeskyInferenceMethod, #this method takes too long to run
                  #KLCovarianceInferenceMethod, #this method takes too long to run
                  ]

likelihoods =[
            LogitDVGLikelihood(), #KLDual method uses a likelihood class that supports dual variational inference
            LogitLikelihood(),        
            LogitVGLikelihood(), #KL method uses a likelihood class that supports variational inference
            LogitVGLikelihood(), #KL method uses a likelihood class that supports variational inference
            #LogitVGLikelihood(), #KL method uses a likelihood class that supports variational inference
            #LogitVGLikelihood(), #KL method uses a likelihood class that supports variational inference
            ]

minimizers =[
            KLDualInferenceMethodMinimizer,
            None, #using default minimizer
            LBFGSMinimizer,
            LBFGSMinimizer,
            #LBFGSMinimizer,
            #LBFGSMinimizer,
            ]

linesearches=[
            BACKTRACKING_ARMIJO,
            None, #using default line search method
            BACKTRACKING_STRONG_WOLFE,
            BACKTRACKING_STRONG_WOLFE,
            #BACKTRACKING_STRONG_WOLFE,
            #BACKTRACKING_STRONG_WOLFE,
            ]

col_size=8
lscale_min=0.0
lscale_max=5.0
lsigma_min=0.0
lsigma_max=5.0
delta=0.5
scale=5.0

lscale_list = np.arange(lscale_min, lscale_max, delta)
lsigma_list = np.arange(lsigma_min, lsigma_max, delta*scale)
lScale, lSigma = np.meshgrid(lscale_list, lsigma_list)
width=len(likelihoods)/2
f, plots =plt.subplots(width, 2, figsize=(col_size*2,col_size*width))

approx_bit_plot(inference_methods, minimizers, linesearches, likelihoods, x_train, y_train,  x_test, y_test, plots, lScale, lSigma, B)

plt.show()
------------------

AttributeError: 'int' object has no attribute 'startswith'
```

**Comment by deveshnag1** [comment]
@vigsterkr It seems there was another error that I overlooked towards the end. I'll send a PR ASAP. Sorry for the mistake.
