### ISSUE TITLE
trained_model_serialization_unittest.cc.py fails with python 35

### ISSUE THREAD

**Issue by vigsterkr** [shogun-toolbox/shogun#4088]
```[ 54%] Generating trained_model_serialization_unittest.cc
Traceback (most recent call last):
  File "/cluster/home/galv/shogun/tests/unit/base/trained_model_serialization_unittest.cc.py", line 137, in <module>
    outputText = entry(TEMPLATE_FILE, input_file, config_file)
  File "/cluster/home/galv/shogun/tests/unit/base/trained_model_serialization_unittest.cc.py", line 116, in entry
    and not is_guarded(header, guards)\
  File "/cluster/home/galv/shogun/tests/unit/base/trained_model_serialization_unittest.cc.py", line 45, in is_guarded
    guards = re.findall('#ifdef (\w+)', header.read().lower())
  File "/cluster/home/galv/anaconda2/envs/shogun-mkl-35/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 290: ordinal not in range(128)
tests/unit/CMakeFiles/shogun-serialization-unit-test.dir/build.make:82: recipe for target 'tests/unit/trained_model_serialization_unittest.cc' failed
make[2]: *** [tests/unit/trained_model_serialization_unittest.cc] Error 1
``````

**Comment by salonirk11** [comment]
@vigsterkr can i work on this?

**Comment by vigsterkr** [comment]
@salonirk11 sure feel free! go ahead and open a PR :)

**Comment by salonirk11** [comment]
It’s probably due to encoding we have to enforce utf 8 here.
I am having troubles in recreating it locally. Could u help me out here?

**Comment by luisffranca** [comment]
Hi @vigsterkr !

I've tried a few things but couldn't reproduce this issue. I'm using Python 3.5.2 on Ubuntu 16.04.

I've built shogun using the following cmake options:

`cmake -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_PACKAGES_PATH=/usr/local/lib/python3.5/dist-packages -DINTERFACE_PYTHON=ON -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=ON -DBUILD_DASHBOARD_REPORTS=ON -DBUILD_META_EXAMPLES=ON .. `

and ran the tests, which passed. 

Then, at ./shogun/build/tests/unit , I've ran the following command shown in `tests/unit/CMakeFiles/shogun-serialization-unit-test.dir/build.make` :

`python3 ./shogun/tests/unit/base/trained_model_serialization_unittest.cc.py ./shogun/tests/unit/base/trained_model_serialization_unittest.cc.jinja2 ./shogun/build/src/shogun/tags trained_model_serialization_unittest.cc ./shogun/build/src/shogun/lib/config.h`

which ran successfully.  Do you know what else could I do in order to reproduce it?

Thanks!
