### ISSUE TITLE
install shogun fail.

### ISSUE THREAD

**Issue by yyanwcy521** [shogun-toolbox/shogun#4197]
the error:
src/interfaces/python/CMakeFiles/_interface_python.dir/build.make:73: recipe for target 'src/interfaces/python/CMakeFiles/_interface_python.dir/shogunPYTHON_wrap.cxx.o' failed
make[2]: *** [src/interfaces/python/CMakeFiles/_interface_python.dir/shogunPYTHON_wrap.cxx.o] Error 1
CMakeFiles/Makefile2:465: recipe for target 'src/interfaces/python/CMakeFiles/_interface_python.dir/all' failed
make[1]: *** [src/interfaces/python/CMakeFiles/_interface_python.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

i follow the steps:
1.mkdir build
2.cd build
3.cmake -DINTERFACE_PYTHON=ON ..
then what happend as above error.
what should i do? thank you.

**Comment by yyanwcy521** [comment]
i install at ubuntu 16.04

**Comment by karlnapf** [comment]
We would either need a full error message (use a github gist), or you can install the binary version of shogun if you have trouble compiling it from scratch. There is both a ppa and a conda package

**Comment by yyanwcy521** [comment]
Thank you very much!
I reinstall my system and only install ppa,then according to the steps:
   cmake  -DINTERFACE_PYTHON=ON ..
   make 
   sudo make install 
the  progress bar is 100% ,like this:
 [100%] Linking CXX executable converter/cpp-converter-independent_component_analysis_fast
[100%] Built target cpp-converter-independent_component_analysis_fast
Scanning dependencies of target cpp-binary-averaged_perceptron
[100%] Building CXX object examples/meta/cpp/CMakeFiles/cpp-binary-averaged_perceptron.dir/binary/averaged_perceptron.cpp.o
[100%] Linking CXX executable binary/cpp-binary-averaged_perceptron
[100%] Built target cpp-binary-averaged_perceptron
Scanning dependencies of target cpp-statistical_testing-quadratic_time_maximum_mean_discrepancy
[100%] Building CXX object examples/meta/cpp/CMakeFiles/cpp-statistical_testing-quadratic_time_maximum_mean_discrepancy.dir/statistical_testing/quadratic_time_maximum_mean_discrepancy.cpp.o
[100%] Linking CXX executable statistical_testing/cpp-statistical_testing-quadratic_time_maximum_mean_discrepancy
[100%] Built target cpp-statistical_testing-quadratic_time_maximum_mean_discrepancy
[100%] Compiled generated cpp examples
[100%] Built target build_cpp_meta_examples

But when I import shogun in Python,there something wrong:
the error :
>>> import shogun
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/shogun.py", line 20, in <module>
    _shogun = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/shogun.py", line 19, in swig_import_helper
    return importlib.import_module('_shogun')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: /usr/local/lib/python2.7/dist-packages/_shogun.so: undefined symbol: _ZNK6shogun9CSGObject6equalsEPKS0_

I don't know what to do. And I just want to import some mudule to run some code, like:

from shogun.Features import *
from shogun.Kernel import *
from shogun.Classifier import *
from shogun.Evaluation import *
from modshogun import StringCharFeatures, RAWBYTE
from modshogun import MulticlassLabels
from shogun.Kernel import SSKStringKernel

When I install shogun successfully ,  modshogun module  exist?

**Comment by grg121** [comment]
Are you using python 2 or python 3 (?) In Ubuntu17 I had that problem: When installing shogun in the way you do, I could import it in python2 but no in python 3... I had to execute cmake in this way:

`cmake -DINTERFACE_PYTHON=ON BUILD_META_EXAMPLES=ON -DENABLE_TESTING=ON -DCMAKE_BUILD_TYPE=Debug -DBUILD_DASHBOARD_REPORTS=ON DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.6 -DPYTHON_PACKAGES_PATH=/usr/local/lib/python3.6/dist-packages `.. ``

to get shogun working in python 3

Some notes in  [my blog](https://grg121.github.io/2018/02/Python-doesn't-find-shogun.html)

:)

**Comment by grg121** [comment]
ps: -BUILD_META_EXAMPLES,  -DBUILD_DASHBOARD_REPORTS=ON , -DCMAKE_BUILD_TYPE=Debug and -DENABLE_TESTING=ON are not necessary.

**Comment by vigsterkr** [comment]
@yyanwcy521 if you just want to use shogun from python why dont you use either the ppa package or the conda package?

**Comment by vigsterkr** [comment]
@yyanwcy521 on the other hand can you paste the content of the `build/src/shogun/lib/versionstring.h` file here

**Comment by gf712** [comment]
seems like we will never know what happened here!
