### ISSUE TITLE
Issue with importing shogun when manually compiled in Ubuntu.

### ISSUE THREAD

**Issue by born-2learn** [shogun-toolbox/shogun#4472]
HI
I tried to compile shogun manually in ubuntu by following the instructions given in `doc/readme/INSTALL.md` file using the cmake command(for python3):

```python
cmake -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYTHON_PACKAGES_PATH=/usr/local/lib/python3.6/dist-packages -DINTERFACE_PYTHON=ON ..` 
followed by `make` and `sudo make install
```

The log files are:
[CMakeError.log](https://github.com/shogun-toolbox/shogun/files/2769322/CMakeError.log)
[CMakeOutput.log](https://github.com/shogun-toolbox/shogun/files/2769323/CMakeOutput.log)

The build was successful.

I added `shogun.py` to pythonpath
`export PYTHONPATH="~/shogun/build/src/interfaces/python/shogun.py:$PYTHONPATH"`
and made the shogun library visible to the system by:
`export LD_LIBRARY_PATH="/usr/local/lib/libshogun.so.*:$LD_LIBRARY_PATH"`

After running an example:
`python ~/shogun/build/examples/meta/python/regression/linear_ridge_regression.py`
Here's the errors:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/shogun.py", line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libshogun.so.18: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "linear_ridge_regression.py", line 2, in <module>
    from shogun import csv_file
  File "/usr/local/lib/python3.6/dist-packages/shogun.py", line 20, in <module>
    _shogun = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/shogun.py", line 19, in swig_import_helper
    return importlib.import_module('_shogun')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libshogun.so.18: cannot open shared object file: No such file or directory
```

I would really appreciate some help.

Also, is it advisable to install shogun using *Ready to install* Ubuntu package, and then follow the **'git flow workflow'** for beginning with **Google Summer of Code** Shogun?
Are Python3 bindings available for ubuntu?

**Comment by vigsterkr** [comment]
```export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"```

as it's a variable that holds paths and not filenames.

**Comment by born-2learn** [comment]
It worked, thanks @vigsterkr
